import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { ArrowRight, Bug, ClipboardCheck, Phone, Rat, ShieldCheck } from "lucide-react";
import { EstimateForm } from "@/components/estimate-form";

const phone = "559-321-6230";
const phoneHref = "tel:+15593216230";

export default function Home() {
  return <div className="page-shell">
    <header className="site-header"><nav className="nav" aria-label="Main navigation"><Link className="brand" href="/"><Image src="/bug-dude-logo.svg" alt="The Bug Dude Pest Control" width={820} height={360} priority /></Link><div className="nav-links"><a href="#commercial">Commercial</a><a href="#services">Services</a><a href="#estimate">Request estimate</a></div><a className="phone-link" href={phoneHref}><Phone size={16} aria-hidden /> {phone}</a></nav></header>
    <main>
      <section className="hero"><div className="hero-inner"><div className="hero-copy"><h1>Pest control that keeps <em>business</em> moving.</h1><p>Local Fresno pest control for commercial properties, rentals, and homes. Tell us what’s happening and we’ll help you find the right next step.</p><div className="action-row"><a className="button button-primary" href="#estimate">Request an estimate <ArrowRight size={18} /></a><a className="button button-alt" href="/book">Book service <ArrowRight size={18} /></a><a className="button button-plain" href={phoneHref}><Phone size={18} /> Call</a></div></div><aside className="dispatch" aria-label="Commercial service request overview"><span className="paint-mark">LOCAL<br />TO<br />FRESNO</span><div className="dispatch-body"><p className="dispatch-title">Start a service request</p><div className="request-line"><span>Property</span><strong>Business or rental</strong></div><div className="request-line"><span>Issue</span><strong>Tell us what you’re seeing</strong></div><div className="request-line"><span>Next step</span><strong>Estimate & scheduling</strong></div><div className="availability"><span className="status-dot" />Same-day service when we can make it work</div></div></aside></div></section>
      <section className="call-strip"><div className="call-strip-inner"><span>Need to talk through a pest problem right now?</span><a href={phoneHref}>Call {phone} <ArrowRight size={17} aria-hidden /></a></div></section>
      <section className="commercial-band" id="commercial"><div className="section"><h2>Built for the places Fresno works.</h2><p className="section-intro">From a one-time issue to recurring service needs, make The Bug Dude your first call for a straightforward conversation about your property.</p><div className="property-list"><div><span>01</span>Offices & storefronts</div><div><span>02</span>Restaurants & food service</div><div><span>03</span>Rental & apartment properties</div><div><span>04</span>Warehouses & workspaces</div></div><div className="action-row" style={{ marginTop: 36 }}><Link className="button button-alt" href="/commercial">Explore commercial service <ArrowRight size={18} /></Link></div></div></section>
      <section className="section" id="services"><div className="services-layout"><div><h2>One local call for the pests you don’t want around.</h2><p className="section-intro">We handle common household and property pests. Share your specific issue in the estimate form and we’ll follow up on your needs.</p><Link className="button button-plain" href="/services">View service areas <ArrowRight size={18} /></Link></div><div className="service-list"><Service icon={<Bug />} title="Crawling & flying pests" text="Spiders, ants, roaches, mosquitoes, fleas, ticks, earwigs, bedbugs, and more." /><Service icon={<Rat />} title="Rodent concerns" text="Tell us what you’re seeing around your home, rental, or commercial property." /><Service icon={<ClipboardCheck />} title="Flexible service options" text="One-time service and no-contract options are available to fit your needs." /><Service icon={<ShieldCheck />} title="Follow-up support" text="If you’re not satisfied, we’ll come back at no charge." /></div></div></section>
      <section className="quote-section" id="estimate"><div className="section"><div><h2>Let’s get a look at the problem.</h2><p className="section-intro" style={{ color: "#79301e" }}>Send a concise request for an estimate. For immediate questions, call us during business hours: Monday–Friday, 7:30 AM–4:30 PM.</p><div className="action-row"><a className="button button-plain" href={phoneHref}><Phone size={18} /> Call {phone}</a></div></div><EstimateForm /></div></section>
    </main>
    <footer className="site-footer"><div className="footer-inner"><div className="footer-brand"><Image src="/bug-dude-logo.svg" alt="The Bug Dude Pest Control" width={820} height={360} /><span>Fresno Pest Control</span></div><div className="footer-meta">Monday–Friday, 7:30 AM–4:30 PM<br /><a href={phoneHref}>{phone}</a></div></div></footer>
  </div>;
}

function Service({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <article className="service-item">{icon}<div><h3>{title}</h3><p>{text}</p></div></article>; }
